import java.text.*;
public class FramePizzaCalc extends javax.swing.JFrame {

   DecimalFormat x = new DecimalFormat("##.00");// Creats a new decimal format 
    public FramePizzaCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPizzaCalc = new javax.swing.JLabel();
        labelPizzaDiameter = new javax.swing.JLabel();
        textInputPizzaDiameter = new javax.swing.JTextField();
        labelMessage = new javax.swing.JLabel();
        labelPizzainInches = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelPizzaCalc.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelPizzaCalc.setText("Pizza Price Calculator");

        labelPizzaDiameter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPizzaDiameter.setText("Enter the Diameter of the");
        labelPizzaDiameter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        textInputPizzaDiameter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textInputPizzaDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputPizzaDiameterActionPerformed(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMessage.setText("This is a pizza price calculator program");

        labelPizzainInches.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPizzainInches.setText("Pizza in Inches");

        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPizzaDiameter)
                    .addComponent(labelPizzainInches))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(textInputPizzaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPizzaCalc)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonCalculate)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMessage)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelPizzaCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textInputPizzaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelPizzainInches)
                        .addComponent(labelPizzaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buttonCalculate)
                .addGap(47, 47, 47)
                .addComponent(labelMessage)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        labelPizzaDiameter.getAccessibleContext().setAccessibleName("Enter the Diameter of the\nPizza in inches");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textInputPizzaDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputPizzaDiameterActionPerformed
        
    }//GEN-LAST:event_textInputPizzaDiameterActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        double diameterOfPizza; // Creates a double variable called diameterOfPizza
        double labourCost;// Creates a double variable called labourCost
        double storeCost;// Creates a double variable called storeCost
        double materialsCost;// Creates a double variable called materialsCost
        double totalCost; // Creates a double variable called totalCost
        
        diameterOfPizza = Double.parseDouble(textInputPizzaDiameter.getText()); // Changes diameterOfPizza into a string to get data from textInputPizzaDiameter
        materialsCost = 0.50 * diameterOfPizza; // Assigns 0.50 * diameterOfPizza to materialsCost
        labourCost = 1.00; // Assigns 1.00 to labourCost
        storeCost = 1.50; // Assigns 1.50 to storeCost
        totalCost = materialsCost + labourCost + storeCost; // Assigns the values of materialsCost, LabourCosts and storeCost and adds them all up
                
        labelMessage.setText("The cost of the Pizza is $" + x.format(totalCost)); // Displays a message when you hit the Calculate button
    }//GEN-LAST:event_buttonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePizzaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePizzaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePizzaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePizzaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePizzaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelPizzaCalc;
    private javax.swing.JLabel labelPizzaDiameter;
    private javax.swing.JLabel labelPizzainInches;
    private javax.swing.JTextField textInputPizzaDiameter;
    // End of variables declaration//GEN-END:variables
}
